name: Weekly Release Email

on: push
# on:
#   release:
#     types: [published]

jobs:
  send-email:
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.get_releases.outputs.releases }} 
      releases1: ${{ steps.get_releases1.outputs.releases1 }} 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # - name: Get Last Week's Releases
      #   id: get_releases
      #   run: |
      #     last_week=`date -d "last week" "+%Y-%m-%d"`
      #     echo releases=$(curl -s https://api.github.com/repos/smit-darji/RELESE_EMAIL/releases?since=$last_week | jq -r '.[].body') >> $GITHUB_OUTPUT

      - name: Get Last Week's Releases
        id: get_releases1
        run: |
          last_week=`date -d "last week" "+%Y-%m-%dT%H:%M:%SZ"`
          releases1=$(curl -s "https://api.github.com/repos/smit-darji/RELESE_EMAIL/releases?per_page=100&since=$last_week")
          echo releases1=$(echo $releases1 | jq -r '.[] | {name: .name, tag: .tag_name, url: .html_url, body: .body} | @json' | jq -s .) >>$GITHUB_OUTPUT

      - name: Print reles
        run: echo "${{ steps.get_releases.outputs.releases }}"

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "New Release: ${{ github.event.release.tag_name }}"
          body: ${{ steps.get_releases1.outputs.releases1 }}
          to: "sahilvandra.softvan@gmail.com"
          from: "smit.softvan@gmail.com"