name: Weekly Release Email with format_details
on: push
jobs:
  send-email:
    runs-on: ubuntu-latest
    outputs:
      # releases: ${{ steps.get_releases.outputs.releases }}
      details: ${{ steps.format_details.outputs.details }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      # - name: Get Last Week's Releases
      #   id: get_releases
      #   run: |
      #     last_week=`date -d "last week" "+%Y-%m-%dT%H:%M:%SZ"`

      #     releases=$(curl -s "https://api.github.com/repos/smit-darji/RELESE_EMAIL/releases?per_page=100&since=$last_week")

      #     echo releases=$(echo $releases | jq -r '.[] | {name: .name, tag: .tag_name, url: .html_url, body: .body} | @json' | jq -s .) >> $GITHUB_OUTPUT

          
      # - name: Print
      #   run: |
      #     echo ${{ steps.get_releases.outputs.releases }}
      
      - name: Format release notes
        id: format_details
        run: |
          last_week=`date -d "last week" "+%Y-%m-%dT%H:%M:%SZ"`

          releases=$(curl -s "https://api.github.com/repos/smit-darji/RELESE_EMAIL/releases?per_page=100&since=$last_week")

          echo releases_list=$(echo $releases | jq -r '.[] | {name: .name, tag: .tag_name, url: .html_url, body: .body} | @json' | jq -s .)

          echo "releases_list is ::"
          echo "---------------------"
          echo $releases_list
          echo "---------------------"
          detail=""
          
          for release in $releases_list); do
            name=$(echo $release | jq -r ".name")
            tag=$(echo $release | jq -r ".tag_name")
            url=$(echo $release | jq -r "".html_url")
            body=$(echo $release | jq -r ".body")
            detail+="### $name ($tag)\n"
            detail+="- **URL:** $url\n"
            detail+="- **Description:**\n$body\n\n"
          done
          echo "details  are:::"$detail
          echo details=$detail >> $GITHUB_OUTPUT

      - name: Print
        run: |
          echo detail: ${{ steps.format_details.outputs.details }}

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Weekly Release Update
          body: |
            Hello,

            Here are the releases created in the last week:

            ${{ steps.format_details.outputs.details }} 

            Regards,
            Your GitHub Action
          to: sahilvandra.softvan@gmail.com
          from: smit.softvan@gmail.com
