# name: Send release details

on: push

jobs:
  send_email:
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.get_release_details.outputs.releases }}
      body: ${{ steps.format_email.outputs.body }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release details
        id: get_release_details
        run: |
          releases=$(curl -s "https://api.github.com/repos/smit-darji/RELESE_EMAIL/releases")
          echo releases=$(echo $releases | jq -r '.[] | { name: .name, url: .html_url, published_at: .published_at }') >> $GITHUB_OUTPUT
      - name: Print
        run: |
          echo  ${{ steps.get_release_details.outputs.releases }}

      - name: Format email
        id: format_email
        run: |
          releases=$(curl -s "https://api.github.com/repos/smit-darji/RELESE_EMAIL/releases")

          releases=$(echo $releases | jq -r '.[] | {name: .name, tag: .tag_name, url: .html_url, body: .body,published_at: .published_at} | @json' | jq -s .)

          echo "-----------------"
          echo $releases
          echo "-------"
          body=""
          for release in $(echo "$releases" | jq -c '.[]'); do
            name=$(echo $release | jq -r '.name')
            tag=$(echo $release | jq -r '.tag')
            url=$(echo $release | jq -r '.url')
            published_at=$(echo $release | jq -r '.published_at')
            formatted_date=$(date -d $published_at +'%Y-%m-%d %H:%M:%S %z')
            message="$name   $url     $formatted_date     $tag"
            body="$body $message"
          done
          echo body=$body >> $GITHUB_OUTPUT
      - name: email is 
        run: echo -e ${{ steps.format_email.outputs.body }}

      - name: Send email
        uses: dawidd6/action-send-mail@v2.2.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Release details for ${GITHUB_REPOSITORY}
          body: ${{ steps.format_email.outputs.body }}
          to: sahilvandra.softvan@gmail.com
          from: smit.softvan@gmail.com
