name: Send release details

on: push

jobs:
  send_email:
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.get_release_details.outputs.releases }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release details
        id: get_release_details
        run: |
          releases=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases)
          echo releases=$(echo $releases | jq -r '.[] | { name: .name, url: .html_url, published_at: .published_at, body: .body }') >> $GITHUB_OUTPUT

      - name: Print release details
        run: |
          ${{ steps.get_release_details.outputs.releases }}

      - name: Format email
        id: format_email
        uses: marvinpinto/action-jinja2@v2.1.0
        with:
          data: ${{ steps.get_release_details.outputs.releases }}
          template: |
            {% for release in data %}
            {{ release.name }}
            {{ release.url }}
            {{ release.published_at | strftime('%Y-%m-%d %H:%M:%S %z') }}

            {{ release.body | indent(4) }}

            {% endfor %}

      - name: Send email
        uses: dawidd6/action-send-mail@v2.2.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Release details for ${GITHUB_REPOSITORY}
          body: ${{ steps.format_email.outputs.rendered }}
          to: sahilvandra.softvan@gmail.com
          from: smit.softvan@gmail.com