name: Send release details

on: push

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release details
        id: get_release_details
        run: |
          releases=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases)
          echo "::set-output name=releases::$(echo $releases | jq -r '.[] | { name: .name, url: .html_url, published_at: .published_at, body: .body }')"

      - name: Install Jinja2
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install jinja2-cli

      - name: Format email
        id: format_email
        run: |
          source env/bin/activate
          echo "${{ steps.get_release_details.outputs.releases }}" | jinja2 -e yaml -f - <<EOF
          {% for release in releases %}
          {{ release.name }}
          {{ release.url }}
          {{ release.published_at | strftime('%Y-%m-%d %H:%M:%S %z') }}

          {{ release.body | indent(4) }}

          {% endfor %}
          EOF
        shell: bash

      - name: Send email
        uses: dawidd6/action-send-mail@v2.2.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Release details for ${GITHUB_REPOSITORY}
          body: ${{ steps.format_email.stdout }}
          to: sahilvandra.softvan@gmail.com
          from: smit.softvan@gmail.com