name: Send Latest Release Details

on:  push

jobs:
  send_email:
    runs-on: ubuntu-latest
    outputs:
      message_body: ${{ steps.format_details.outputs.message_body }}
      contents: ${{ steps.read-file.outputs.contents }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install PyGithub jinja2

    - name: Get release details
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        from github import Github
        from jinja2 import Template

        # Create a Github instance
        g = Github()

        # Get a repository by its owner and name
        repo = g.get_repo("smit-darji/RELESE_EMAIL")

        # Get the latest release
        latest_release = repo.get_latest_release()

        # Format the release details as a string
        release_details = f"Release name: {latest_release.title}\nRelease tag: {latest_release.tag_name}\nRelease body: {latest_release.body}"
        template = Template("{{ release_details }}")

        # Render the template with the release details
        email_body = template.render(release_details=release_details)
        print(email_body)

    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Latest Release Details
        body: ${{ steps.get_release_details.outputs.email_body }}
        to: sahilvandra.softvan@gmail.com
        from: smit.softvan@gmail.com