name: Send Latest Release Details

on:  push

jobs:
  send_email:
    runs-on: ubuntu-latest
    outputs:
      message_body: ${{ steps.format_details.outputs.message_body }}
      contents: ${{ steps.read-file.outputs.contents }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install PyGithub jinja2

    - name: Get release details
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        from github import Github
        import jinja2

        # Create a Github instance
        g = Github(os.environ["GITHUB_TOKEN"])

        # Get a repository by its owner and name
        repo = g.get_repo("smit-darji/RELESE_EMAIL")

        # Get the latest release
        latest_release = repo.get_latest_release()

        # Load the Jinja2 template
        template_loader = jinja2.FileSystemLoader(searchpath="./")
        template_env = jinja2.Environment(loader=template_loader)
        template = template_env.get_template("release_email.j2")

        # Render the template with the release details
        email_body = template.render(
            release_name=latest_release.title,
            release_tag=latest_release.tag_name,
            release_body=latest_release.body
        )

        # Store the email body as a workflow output
        print(email_body)
        print("::set-output name=email_body::" + email_body)

    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Latest Release Details
        body: ${{ steps.get_release_details.outputs.email_body }}
        to: sahilvandra.softvan@gmail.com
        from: smit.softvan@gmail.com