name: Weekly Release Notes Email
# on:
#   schedule:
#     # - cron: '0 0 * * 1' # Runs every Monday at 12am UTC
#     - cron: '*/1 * * * *' # Runs every Monday at 12am UTC
on:
  release:
    types: [published]


jobs:
  send-release-notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Generate Release Notes
      run: node generate-release-notes.js

    - name: Send Email
      uses: dawidd6/action-send-mail@v2.2.0
      with:
        server_address: smtp.sendgrid.net
        server_port: 587
        username: ${{ secrets.SENDGRID_USERNAME }}
        password: ${{ secrets.SENDGRID_PASSWORD }}
        subject: "Weekly Release Notes"
        body: ${{ steps.generate-release-notes.outputs.releaseNotes }}
        from: "smit.softvan@gmail.com"
        to: "sahilvandra.softvan@gmail.com"